-d E:\projects\I2C_PWM\gowin_project\spi_dshot\spi_dshot\impl\gwsynthesis\spi_dshot.vg
-p GW1N-1-QFN32-5
-pn GW1N-LV1QN32C5/I4
-cst E:\projects\I2C_PWM\gowin_project\spi_dshot\spi_dshot\src\spi_dshot.cst
-cfg E:\projects\I2C_PWM\gowin_project\spi_dshot\spi_dshot\impl\pnr\device.cfg
-sdc E:\projects\I2C_PWM\gowin_project\spi_dshot\spi_dshot\src\spi_dshot.sdc
-bit
-tr
-ph
-timing
-cst_error
