-d E:\projects\I2C_PWM\gowin_project\i2c_pwm\impl\gwsynthesis\i2c_pwm.vg
-p GW1N-1-QFN32-6
-pn GW1N-LV1QN32C6/I5
-cst E:\projects\I2C_PWM\gowin_project\i2c_pwm\src\i2c_pwm.cst
-cfg E:\projects\I2C_PWM\gowin_project\i2c_pwm\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
